# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20160901_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_id1',
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
