# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20160905_1016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_Cat',
            new_name='SubCategory',
        ),
    ]
