# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20160905_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='p_id',
            new_name='categoryid',
        ),
    ]
